name: BotArchitect

on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          original_issue: 1
          label: "Architect Sync"
          title: "Architect Sync On "
          assignees: "I338916"
          body: |
            ## Sync:

            ## Notes

            ## Points to be discussed

            | Topic            | Details         | Action Item | Status          |
            | ------------- | ------------- | ------------- | ------------- |
            | ..                  |  ..                  | ..                  | ..                   |

            ## Updates
            
            https://github.wdf.sap.corp/I338916/B1CEBotArchitect/issues/

