name: Test

on:
  schedule:
    - cron: '*/6 * * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          original_issue: 42
          issue_url_path: "https://github.com/vickeyksoni/thank-you-action/issues/"
          title: "Architect Sync On "
          assignees: "vickeyksoni"
          body: |
            ## Sync:

            ## Notes

            ## Points to be discussed

            | Topic            | Details         | Action Item | Status          |
            | ------------- | ------------- | ------------- | ------------- |
            | ..                  |  ..                  | ..                  | ..                   |

            ## Updates
            
